### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/contract#39]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] contract_mandate - By @carlosdauden - #113 
- [x] contract - By @StefanRijnhart - #40
- [x] contract_digitized_signature - By @bmw95 - #108 
- [ ] contract_invoice_merge_by_partner
- [x] contract_payment_mode - By @chienandalu - #71 
- [x] contract_recurring_plans > contract_recurring_analytic_distribution - By @cubells - #106 
- [x] contract_show_invoice - By @thinkwelltwd - #54 
- [x] contract_variable_quantity - By @lasley - #44

**Comment by lasley** [comment]
#44 for contract_show_invoice

**Comment by lasley** [comment]
I looked at `contract_show_invoice` and question whether it is still necessary? What's the difference between it and the existing `Show Recurring Invoices` button in the contract already?

![image](https://cloud.githubusercontent.com/assets/7397578/20897115/9b22b550-bad5-11e6-953d-9f50c695572f.png)

**Comment by pedrobaeza** [comment]
You can do invoices that are not generated from the contract, but linked to the analytic account. Maybe an smart-button is better option. Integrated in the main module?, uhm, I don't know.

**Comment by lasley** [comment]
That's kind of what I'm wondering too really - smart button also came to my mind. I almost just 1:1 upgraded the module then figured it would probably be best to determine that before doing the work.

I'm trying to think of a use case of anyone not wanting this functionality in the base module. It seems to me if you have the contracts, you would also always want the usability added of having the smart button?

**Comment by pedrobaeza** [comment]
I also think it can be integrated now that we don't depend on an Odoo module.

**Comment by lasley** [comment]
Sweet I'll do that at some point this week & will deprecate the module in the PR. You can tag that one to me please.

**Comment by m3dbedb** [comment]
After installation of  "Contracts Management - Recurring" module, I create contract for demo customer agrolait, and when I try to create and save invoice for the contract, odoo say 
 " File "C:\Program Files (x86)\Odoo 10.0\server\odoo\fields.py", line 2011, in convert_to_cache
ValueError: Wrong value for account.invoice.analytic_account_ids: 7"
Same error found in runbot of odoo community.

**Comment by lasley** [comment]
@m3dbedb - please create an issue for your problem report instead of hijacking an unrelated one

**Comment by pedrobaeza** [comment]
Closing as old version
