### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/contract#880]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] agreement_rebate_partner_company_group - By @stefan-tecnativa - #980
- [x] contract - By @wpichler - #887
- [ ] contract_invoice_start_end_dates - By @JesusValdez96 - #950
- [x] contract_mandate - By @adriapalleja - #1070
- [x] contract_payment_auto - By @9184Lucky - #1231
- [x] contract_payment_mode - By @carolinafernandez-tecnativa - #996
- [ ] contract_price_revision - By @houzefa-abba - #1038
- [x] contract_queue_job - By @luisDIXMIT - #1077
- [ ] contract_sale - By @CRogos - #949
- [ ] contract_sale_generation - By @JesusValdez96 - #955
- [x] contract_update_last_date_invoiced - By @edlopen - #1147
- [x] contract_variable_qty_timesheet - By @danypr92 - #1110
- [x] contract_variable_quantity - By @carolinafernandez-tecnativa - #1027
- [x] product_contract - By @Rad0van - #959
- [x] subscription_oca - By @carolina-domatix - #1029

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by jado95** [comment]
Hi, it is possible update module contract_sale with #915?

**Comment by JesusValdez96** [comment]
Please add the missing module contract_invoice_start_end_dates to the list.
PR here: https://github.com/OCA/contract/pull/950

**Comment by CRogos** [comment]
Continuing contract_sale in #949

**Comment by maisim** [comment]
Hi !
I tried to backport product_contract from 17 (https://github.com/OCA/contract/pull/1090) rather than migrate from 15 (https://github.com/OCA/contract/pull/959), thinking it would be more up to date. This is done quite easily. Does this suit you in principle or would you prefer that we continue on the migration from 15.0 (https://github.com/OCA/contract/pull/959) ?

cc @Rad0van what do you think?

**Comment by Rad0van** [comment]
> Hi !
> I tried to backport product_contract from 17 (https://github.com/OCA/contract/pull/1090) rather than migrate from 15 (https://github.com/OCA/contract/pull/959), thinking it would be more up to date. This is done quite easily. Does this suit you in principle or would you prefer that we continue on the migration from 15.0 (https://github.com/OCA/contract/pull/959) ?
> 
> cc @Rad0van what do you think?
> 

AFAIK port to 17 is based (at least partially) on my port to 16. So I wouldn't expect any major differences. I just need to finish two or three contents on 16. Will do it today.

**Comment by danypr92** [comment]
Hi!

I attempted to backport the contract_variable_qty_timesheet module from version 15 to version 16 (see PR #1110). While I found a merge request porting the same module to version 17, I couldn't find any reference for version 16.

Please add the module and the PR to the list.

Thanks!
